# Generated by Django 4.1.2 on 2023-02-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'habit',
            },
        ),
        migrations.CreateModel(
            name='Soil_Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'soil moisture',
            },
        ),
        migrations.CreateModel(
            name='Soil_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'soil type',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Sun_Exposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sun exposure',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plant_tip',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pronunciation', models.CharField(blank=True, max_length=100, null=True)),
                ('aliases', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('zone', models.IntegerField(default=0)),
                ('min_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('spread', models.CharField(blank=True, max_length=50, null=True)),
                ('growth_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('companion_plant', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.category')),
                ('habit', models.ManyToManyField(blank=True, to='plants.habit')),
                ('soil_moisture', models.ManyToManyField(blank=True, to='plants.soil_moisture')),
                ('soil_type', models.ManyToManyField(blank=True, to='plants.soil_type')),
                ('subcategory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.subcategory')),
                ('sun_exposure', models.ManyToManyField(blank=True, to='plants.sun_exposure')),
                ('tips', models.ManyToManyField(blank=True, to='plants.tip')),
            ],
            options={
                'db_table': 'plant_data',
            },
        ),
    ]
