# Generated by Django 4.1.2 on 2023-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_category_alter_plant_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
