# Generated by Django 4.1.2 on 2023-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_plant_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='tips',
        ),
        migrations.AddField(
            model_name='plant',
            name='tips',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
