# Generated by Django 4.1.2 on 2023-02-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_remove_plant_tips_plant_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='tips',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
