# Generated by Django 4.1.2 on 2023-02-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plant_photo_1_plant_photo_2_plant_photo_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='uses_characteristics',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
