# Generated by Django 4.1.2 on 2023-02-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_uses_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='zone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
