# Generated by Django 4.1.2 on 2023-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_alter_plant_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
