# Generated by Django 4.1.2 on 2023-02-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_plant_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image_data',
        ),
    ]
