# Generated by Django 4.1.2 on 2023-03-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_remove_plant_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='QR')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='qr_code1',
            field=models.ManyToManyField(blank=True, null=True, to='plants.qrcode'),
        ),
    ]
