# Generated by Django 4.1.2 on 2023-03-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_qrcode_plant_qr_code1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='qr_code1',
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
